### ISSUE TITLE
keylogger usage? 

### ISSUE THREAD

**Issue by 1N3** [xtr4nge/FruityC2-Client#1]
Trying to figure out the keylogger command usage. Tried running just keylogger or keylogger chrome.exe or keylogger <PID> but just get an error saying "I don't know what to do with this command". 

Is there a usage example you can provide for this?

**Comment by xtr4nge** [comment]
Hi 1N3,
That is because Keylogger was not implemented as part of the inbuilt options yet:
https://github.com/xtr4nge/FruityC2-Client/wiki (search: keylogger)

But you can load any module, for example:
https://github.com/PowerShellMafia/PowerSploit/blob/master/Exfiltration/Get-Keystrokes.ps1
or
https://www.tarlogic.com/en/blog/how-to-create-keylogger-in-powershell/
or any other ;)

You can import the module and run it as powershell_job. I will try to make a quick tutorial in the next few days.

regards,

**Comment by 1N3** [comment]
yeah, that would be awesome. I'm having trouble getting any of the powershell modules to run so that would help as well! btw.. awesome project! Really like it so far.. 👍

**Comment by xtr4nge** [comment]
Cool, glad that you like it. All comments and feedback is welcome.
I will try to create a tutorial about importing, using and creating external modules

Thanks and regards,

**Comment by xtr4nge** [comment]
Hi 1N3,
Here you have a Tutorial on how to use external modules ;)
https://github.com/xtr4nge/FruityC2-Client/wiki/FruityC2-Import-Modules-(PowerShell)

Let me know if this helped
regards,

**Comment by 1N3** [comment]
hey man, appreciate the tutorial here... definitely helps. However, I still can't get the keylogger working using the exact steps in the tutorial. I was however able to run other powershell modules just fine so I'm not sure if there's something specific with my setup that is causing the problem or something else. Either way, I'll keep testing to see what I can find out. Thanks for the help!
